//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int id { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<int> Position { get; set; }
        public string Firstname { get; set; }
        public string MI { get; set; }
        public string Lastname { get; set; }
        public string SSS { get; set; }
        public string Tin { get; set; }
        public string PhilHealth { get; set; }
        public string PagIbig { get; set; }
        public string DOB { get; set; }
        public string Parent { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
        public Nullable<int> Status { get; set; }
        public string ImagePic { get; set; }
        public byte[] Signature { get; set; }
    
        public virtual EPosition EPosition { get; set; }
        public virtual Status Status1 { get; set; }
    }
}
