//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proms.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        public int id { get; set; }

        [Required]
        public string StudentID { get; set; }
        
        [Required]
        public string Firstname { get; set; }

        public string MI { get; set; }

        [Required]
        public string Lastname { get; set; }

        public Nullable<int> Course { get; set; }
        public Nullable<int> GradeLevel { get; set; }
        public Nullable<int> BatchYear { get; set; }

        [Required]
        public string Parent { get; set; }

        [Required]
        public string Address { get; set; }

        [Required]
        public string Contact { get; set; }
        public Nullable<int> Status { get; set; }

        public string ImagePic { get; set; }
        public byte[] Signature { get; set; }
    
        public virtual SBY SBY { get; set; }
        public virtual SCourse SCourse { get; set; }
        public virtual SGrdl SGrdl { get; set; }
        public virtual Status Status1 { get; set; }
    }
}
